import Head from 'next/head';
import * as React from 'react'
import Mainpage from '~/pages/main/mainpage';

export default function Home() {

  return (
    <>
      <Head>
        <title>Trial-Task</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Mainpage />     
    </>
  );
}